# Generated by Django 3.0.1 on 2021-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_inputimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pics')),
            ],
        ),
        migrations.DeleteModel(
            name='InputImage',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
