# Generated by Django 3.1.7 on 2021-03-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210203_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='input_images')),
            ],
        ),
    ]
